---
image: docker:19.03.12

services:
  - name: docker:19.03.12-dind
    alias: docker

stages:
  - tox
  - build
  - release

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

lint-and-test:
  stage: tox
  image: python:3.10-bullseye
  script:
    - pip3 install --upgrade pip setuptools wheel
    - pip3 install --no-cache -r requirements.txt
    - tox
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "**/*.py"
    - when: never

update-changelog:
  stage: build
  image: python:3.8-bullseye
  script:
    - git reset --hard origin/dev && git pull --ff
    - pip install -U commitizen==2.20.5
    - cz changelog
    - git add CHANGELOG.md
    - 'git commit -m "docs: next release updates" || echo "Nothing to be commited"'
    - git push origin -o ci.skip $CI_BUILD_REF_NAME:$CI_COMMIT_REF_NAME || echo "There are no changes to be committed."
  rules:
    - if: $CI_COMMIT_REF_NAME == 'dev' && $CI_PIPELINE_SOURCE != 'merge_request_event'

tag-main:
  stage: release
  image: python:3.8-bullseye
  script:
    - git reset --hard origin/main && git pull --ff
    - pip install -U commitizen==2.20.5
    - cz bump --changelog || (echo "Bump not possible; no suitable commits." && exit 0)
    - git push origin -o ci.skip $CI_BUILD_REF_NAME:$CI_COMMIT_REF_NAME
    - git push origin -o ci.skip $CI_BUILD_REF_NAME:dev
    - git push origin $(cz version --project)
  rules:
    - if: $CI_COMMIT_REF_NAME == main'
