name: Bump version, tag, generate changelog and merge back to dev

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    if: "!contains(github.event.head_commit.message, 'release')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Run commitizen
        run: |
          uv venv
          uv add commitizen
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          .venv/bin/cz bump --yes --changelog || (echo "Bump not possible" && exit 0)
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: main
          tags: true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: dev
